name: Node CI

on:
  push:
    branches:
    - master
    - develop
    - gh-action

  pull_request:
    branches:
      - "*"

jobs:
  yarncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install -g yarn
      - run: yarn install --ignore-scripts --ignore-engines
      - run: test -z "$(git diff -- yarn.lock)" || (echo 'Please run yarn and commit all changes to yarn.lock'; false)

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    name: Node v${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn bootstrap
    - run: yarn test
