name: Node CI

on:
  push:
    branches:
    - master
    - develop

  pull_request:
    branches:
      - "*"

jobs:
  yarncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install -g yarn
      - run: yarn install --ignore-scripts --ignore-engines
      - run: test -z "$(git diff -- yarn.lock)" || (echo 'Please run yarn and commit all changes to yarn.lock'; false)

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    name: Node v${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn bootstrap
    - run: yarn test

  slack_notification:
    needs: [yarncheck, build]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: 8398a7/action-slack@v3
        continue-on-error: true
        with:
          channel: '#truffle-ci-notifications'
          status: ${{ job.status }}
          fields: commit,author,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork
